version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    env_file:
      - .env.compose
    container_name: api
    volumes:
      - ./.env:/opt/app/.env
    ports:
      - 3002:3000
    networks:
      - myNetwork
